In [1]:
import tensorly as tl
import numpy as np

In [2]:
tensor = tl.tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                    [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                    [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                    [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                    [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
# tensor3 = [tensor, tensor, tensor]
[m,n] = tensor.shape
tensor3 = np.array([tensor,tensor+1])
tensor3.shape

(2, 12, 12)

In [3]:
tensor3[0]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
from tensorly.decomposition import tucker
core, factors = tucker(tensor, rank=[4, 3])
core.shape
len(factors)
[f.shape for f in factors]

C:\Users\Hamed\anaconda3\lib\site-packages\tensorly\backend\core.py:786: RuntimeWarning: divide by zero encountered in true_divide
  U = np.dot(matrix, V) *  np.where(np.abs(S) <= np.finfo(S.dtype).eps, 0, 1/S)[None, :]


[(12, 4), (12, 3)]

In [48]:
import numpy as np
facs = [f for f in factors]
A = np.matmul(np.matmul(facs[0],core),facs[1].T)
A.round(2)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -0., -0., -0.,  1.,  1.,  1.,  1., -0., -0., -0.,  0.],
       [ 0., -0., -0., -0.,  1.,  1.,  1.,  1., -0., -0., -0.,  0.],
       [ 0., -0., -0., -0.,  1.,  1.,  1.,  1., -0., -0., -0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
       [ 0., -0., -0., -0.,  1.,  1.,  1.,  1., -0., -0., -0.,  0.],
       [ 0., -0., -0., -0.,  1.,  1.,  1.,  1., -0., -0., -0.,  0.],
       [ 0., -0., -0., -0.,  1.,  1.,  1.,  1., -0., -0., -0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [23]:
facs[0]

array([[ 0.00000000e+00,  9.71445147e-17],
       [-2.27675853e-01, -3.38866305e-01],
       [-2.27675853e-01, -3.38866305e-01],
       [-2.27675853e-01, -3.38866305e-01],
       [-4.15024769e-01,  2.78844833e-01],
       [-4.15024769e-01,  2.78844833e-01],
       [-4.15024769e-01,  2.78844833e-01],
       [-4.15024769e-01,  2.78844833e-01],
       [-2.27675853e-01, -3.38866305e-01],
       [-2.27675853e-01, -3.38866305e-01],
       [-2.27675853e-01, -3.38866305e-01],
       [ 0.00000000e+00,  0.00000000e+00]])

In [6]:
(weight, factors) = CPTensor

f3 = factors[0]

print(np.round(f3))


[[ 7.]
 [18.]]
